// Generated by CoffeeScript 1.7.1
(function() {
  var app;

  app = angular.module("TinyHabits", ["LocalStorageModule", "ngRoute"]);

  app.config([
    '$routeProvider', function($routeProvider) {
      return $routeProvider.when('/user', {
        templateUrl: "user.html",
        controller: "UserInfoController"
      }).when('/habits', {
        templateUrl: "habits.html",
        controller: "HabitsInfoController"
      }).when('/log', {
        templateUrl: "log.html",
        controller: "HabitsLogController"
      }).otherwise({
        redirectTo: '/user'
      });
    }
  ]);

  app.directive("habitform", function() {
    return {
      link: function(scope, element, attrs) {
        var stats;
        stats = scope.habit.stats[scope.currUTCdate];
        scope.habitValue = stats ? stats.status : null;
        return scope.updateValue = function(event) {
          var newVal;
          newVal = event.target.value;
          if (!scope.habit.stats[scope.currUTCdate]) {
            scope.habit.stats[scope.currUTCdate] = {};
          }
          return scope.habit.stats[scope.currUTCdate]["status"] = newVal;
        };
      },
      restrict: "E",
      templateUrl: "form.html"
    };
  });

  app.factory('currUTCdate', function() {
    var currDate;
    currDate = new Date();
    return [currDate.getUTCFullYear(), currDate.getUTCMonth(), currDate.getUTCDate()].join('-');
  });

  app.controller('HabitsInfoController', [
    "$scope", "localStorageService", "currUTCdate", function($scope, localStorageService, currUTCdate) {
      var defaultHabit;
      defaultHabit = {
        description: "",
        stats: {}
      };
      $scope.newHabit = defaultHabit;
      $scope.habits = localStorageService.get("habits" || []);
      $scope.addHabit = function() {
        if ($scope.newHabit) {
          console.log($scope.newHabit);
          $scope.habits.push($scope.newHabit);
          localStorageService.set("habits", $scope.habits);
          return $scope.newHabit = defaultHabit;
        }
      };
      return $scope.deleteHabit = function(index) {
        $scope.habits.splice(index, 1);
        return localStorageService.set("habits", $scope.habits);
      };
    }
  ]);

  app.controller('HabitsLogController', [
    "$scope", "localStorageService", "currUTCdate", function($scope, localStorageService, currUTCdate) {
      $scope.currUTCdate = currUTCdate;
      $scope.habits = localStorageService.get("habits" || []);
      $scope.habitHistory = null;
      $scope.$watch("habits", function(newVal, oldVal) {
        return localStorageService.set("habits", $scope.habits);
      }, true);
      return $scope.showHistory = function(index) {
        return $scope.habitHistory = $scope.habits[index];
      };
    }
  ]);

  app.controller('UserInfoController', [
    "$scope", "localStorageService", "currUTCdate", function($scope, localStorageService, currUTCdate) {
      var defaultUser;
      defaultUser = {
        name: "",
        age: "",
        bio: "",
        date_joined: currUTCdate
      };
      $scope.user = (localStorageService.get("user")) || defaultUser;
      $scope.saveUser = function() {
        console.log($scope.user);
        return localStorageService.set("user", $scope.user);
      };
      $scope.resetUser = function() {
        localStorageService.remove("user");
        return $scope.user = defaultUser;
      };
      $scope.userExists = function() {
        if (localStorageService.get("user")) {
          return true;
        } else {
          return false;
        }
      };
      return $scope.hideGreeting = function() {
        if (localStorageService.get("user")) {
          return !angular.equals(localStorageService.get("user"), $scope.user);
        } else {
          return true;
        }
      };
    }
  ]);

}).call(this);
